"""One-page PDF report for a prediction (reportlab)."""
from __future__ import annotations

import base64
import binascii
import datetime
import io
from typing import Dict

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

DISCLAIMER = "Educational prototype. Not a medical device. Not for clinical use."


def _image_from_b64(b64: str, width_cm: float):
    """Validate and decode one base64 PNG; returns a reportlab Image or None."""
    try:
        raw = base64.b64decode(b64, validate=True)
        with PILImage.open(io.BytesIO(raw)) as im:
            im.verify()
    except (binascii.Error, ValueError, OSError):
        return None
    with PILImage.open(io.BytesIO(raw)) as im:
        w, h = im.size
    return Image(io.BytesIO(raw), width=width_cm * cm, height=width_cm * cm * h / w)


def build_pdf(result: Dict) -> bytes:
    """Build the PDF from a prediction result dictionary (as returned by /api/predict)."""
    if not isinstance(result, dict) or "stage_name" not in result or "probabilities" not in result:
        raise ValueError("Invalid prediction data.")
    styles = getSampleStyleSheet()
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.HexColor("#555555"))
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm, topMargin=1.8 * cm,
                            bottomMargin=1.8 * cm, title="OcuGrade screening report")
    story = [Paragraph("OcuGrade - retinal screening report", styles["Title"]),
             Paragraph(DISCLAIMER, ParagraphStyle("warn", parent=styles["BodyText"], textColor=colors.HexColor("#b45309"))),
             Paragraph(f"Generated: {datetime.datetime.now():%Y-%m-%d %H:%M}", small), Spacer(1, 0.4 * cm)]

    conf = float(result.get("confidence", 0))
    story.append(Paragraph(f"<b>Predicted stage:</b> {int(result.get('stage', 0))} - {_esc(result['stage_name'])}", styles["Heading2"]))
    story.append(Paragraph(f"<b>Confidence:</b> {conf:.1%} &nbsp;&nbsp; <b>Triage label:</b> {_esc(result.get('triage', ''))}",
                           styles["BodyText"]))
    if result.get("low_confidence"):
        story.append(Paragraph("<b>Low confidence: needs human review.</b>", styles["BodyText"]))
    story.append(Paragraph(f"<b>Suggested action:</b> {_esc(result.get('action', ''))} <i>(illustrative only)</i>",
                           styles["BodyText"]))
    for w in result.get("quality_warnings", []) or []:
        story.append(Paragraph(f"Image quality note: {_esc(w)}", small))
    story.append(Spacer(1, 0.3 * cm))

    imgs = result.get("images", {}) or {}
    row, labels = [], []
    for key, label in (("original", "Original"), ("clahe", "CLAHE enhanced"), ("overlay", "Grad-CAM overlay")):
        im = _image_from_b64(imgs.get(key, ""), 5.2) if imgs.get(key) else None
        if im is not None:
            row.append(im)
            labels.append(Paragraph(label, small))
    if row:
        t = Table([row, labels])
        t.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
        story += [t, Spacer(1, 0.4 * cm)]

    data = [["Class", "Probability"]] + [[_esc(p["name"]), f"{float(p['probability']):.1%}"] for p in result["probabilities"]]
    table = Table(data, colWidths=[7 * cm, 4 * cm])
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
                               ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                               ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
                               ("FONTSIZE", (0, 0), (-1, -1), 9)]))
    story += [table, Spacer(1, 0.5 * cm),
              Paragraph("This report was generated by a student coursework prototype (EfficientNetB0 trained on the "
                        "APTOS 2019 dataset). It must not be used for diagnosis or treatment decisions. A qualified "
                        "clinician must review every retinal image.", small)]
    doc.build(story)
    return buf.getvalue()


def _esc(text) -> str:
    """Escape text for reportlab's mini-HTML paragraphs."""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
